services:
  - type: web
    name: pepeleads2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        sync: false

