services:
  - type: web
    name: pepeleads2
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///survey_response.db  # Change to PostgreSQL if needed
        sync: false
